client_id = "00f3c6ab3b24a3dcd552cd526cc8b79b"
name = "Shop Floor Command Center"
application_url = "https://shop-floor-command-center.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_content,write_content,read_online_store_navigation,write_online_store_navigation"

[auth]
redirect_urls = [ "https://shop-floor-command-center.onrender.com/auth/callback" ]
