# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4fa079750cc5d3cd505727b0c47ce940"
name = "shop-floor-command-center"
application_url = "https://shop-floor-command-center.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ "https://shop-floor-command-center.onrender.com/auth/callback" ]
