// geoLibrary.js — Rockhound Studio
// Keys match TARGET_KEYS exactly
// Covers all 37 products in current inventory

const GEO_LIBRARY = {

  // ── YAKIMA JASPER ─────────────────────────────────────────────────
  "yakima jasper": {
    official_name:     "Yakima River Jasper",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy to dull",
    chemical_formula:  "SiO₂",
    rock_composition:  "Microcrystalline quartz with iron oxide and volcanic mineral inclusions",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene — approximately 10–17 million years ago",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Columbia River Basalt Group",
    where_found:       "Yakima River Canyon, Kittitas County, Washington State, USA",
    diaphaneity:       "Opaque",
    rarity_score:      "Regional — PNW endemic",
    stone_story:       "Born in the ancient lava floods of the Columbia River Basalt Group, Yakima jasper carries the volcanic memory of the Pacific Northwest. Each piece is a fragment of a landscape that no longer exists.",
  },

  // ── PICTURE JASPER ────────────────────────────────────────────────
  "picture jasper": {
    official_name:     "Picture Jasper",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy",
    chemical_formula:  "SiO₂",
    rock_composition:  "Microcrystalline quartz with clay, iron oxide, and silica banding",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene — approximately 15 million years ago",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Rhyolitic volcanic deposits",
    where_found:       "Biggs Junction, Oregon and Bruneau, Idaho, USA",
    diaphaneity:       "Opaque",
    rarity_score:      "Uncommon — regionally specific",
    stone_story:       "Picture jasper's landscape-like patterns are ancient desert scenes frozen in silica — each stone a painting made by the earth itself over millions of years.",
  },

  // ── BRECCIATED JASPER ─────────────────────────────────────────────
  "brecciated jasper": {
    official_name:     "Brecciated Jasper",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy",
    chemical_formula:  "SiO₂",
    rock_composition:  "Angular jasper fragments re-cemented by silica or hematite matrix",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal to splintery",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Cenozoic",
    geological_era:    "Variable",
    rock_formation:    "Fault breccia zones in silicified volcanic terrain",
    where_found:       "USA, South Africa, India, Australia",
    diaphaneity:       "Opaque",
    rarity_score:      "Common",
    stone_story:       "Shattered by geological forces and re-cemented by silica, brecciated jasper is a stone of resilience — broken and made whole again by the earth itself.",
  },

  // ── EMERALD GREEN JASPER ──────────────────────────────────────────
  "emerald green jasper": {
    official_name:     "Green Jasper",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy",
    chemical_formula:  "SiO₂",
    rock_composition:  "Microcrystalline quartz colored by chlorite or celadonite inclusions",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Paleozoic",
    geological_era:    "Variable",
    rock_formation:    "Hydrothermal silica replacement zones",
    where_found:       "India, Russia, USA, Germany",
    diaphaneity:       "Opaque",
    rarity_score:      "Uncommon — deep green specimens rare",
    stone_story:       "Deep forest green jasper — a stone of growth and renewal, its color drawn from ancient chlorite minerals locked in silica.",
  },

  // ── JASPER (generic fallback) ─────────────────────────────────────
  "jasper": {
    official_name:     "Jasper",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy to dull",
    chemical_formula:  "SiO₂",
    rock_composition:  "Microcrystalline quartz with mineral impurities (iron oxides, clay, ash)",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal to splintery",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Cenozoic",
    geological_era:    "Variable",
    rock_formation:    "Silicified volcanic or sedimentary deposits",
    where_found:       "Worldwide — USA, India, Russia, Australia, Madagascar",
    diaphaneity:       "Opaque",
    rarity_score:      "Common to uncommon depending on variety",
    stone_story:       "Jasper has been carried as a protective talisman since antiquity — a stone of grounding and endurance found on every continent.",
  },

  // ── BOTSWANA AGATE ────────────────────────────────────────────────
  "botswana agate": {
    official_name:     "Botswana Agate",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline (banded)",
    luster:            "Waxy",
    chemical_formula:  "SiO₂",
    rock_composition:  "Banded microcrystalline quartz with alternating silica layers",
    specific_gravity:  "2.60–2.65",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian — approximately 187 million years ago",
    geological_era:    "Mesozoic — Triassic",
    rock_formation:    "Karoo Supergroup basaltic lava flows",
    where_found:       "Bobonong District, Botswana, Africa",
    diaphaneity:       "Translucent",
    rarity_score:      "Uncommon — single-source locality",
    stone_story:       "From the ancient cradle of humanity, Botswana agate carries banded layers of earth history in soft pinks, grays, and creams — formed in lava flows older than the dinosaurs.",
  },

  // ── MONTANA AGATE ─────────────────────────────────────────────────
  "montana agate": {
    official_name:     "Montana Moss Agate",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy to vitreous",
    chemical_formula:  "SiO₂",
    rock_composition:  "Translucent chalcedony with manganese oxide dendritic inclusions",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Eocene to Miocene — approximately 30–50 million years ago",
    geological_era:    "Cenozoic — Paleogene to Neogene",
    rock_formation:    "Yellowstone River gravel deposits — reworked volcanic ash",
    where_found:       "Yellowstone River gravels, Montana, USA",
    diaphaneity:       "Translucent",
    rarity_score:      "Uncommon — collector grade",
    stone_story:       "Montana agate's ghostly dendrites are manganese oxide that crept through silica like frost on glass — a natural painting formed over millions of years in Yellowstone River gravels.",
  },

  // ── THUNDER AGATE ─────────────────────────────────────────────────
  "thunder agate": {
    official_name:     "Thunder Agate",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline (banded)",
    luster:            "Waxy to vitreous",
    chemical_formula:  "SiO₂",
    rock_composition:  "Banded agate and chalcedony fill within rhyolitic thunderegg nodule",
    specific_gravity:  "2.58–2.65",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene — approximately 10–15 million years ago",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Rhyolitic ash flow tuffs — Pacific Northwest volcanic fields",
    where_found:       "Pacific Northwest, USA — Oregon and Washington",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Uncommon — PNW endemic",
    stone_story:       "Thunder agates form inside thundereggs — volcanic nodules cracked open to reveal worlds within worlds, layer by layer over millions of years.",
  },

  // ── JASPAGATE ─────────────────────────────────────────────────────
  "jaspagate": {
    official_name:     "Jaspagate",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy",
    chemical_formula:  "SiO₂",
    rock_composition:  "Transitional microcrystalline quartz — opaque jasper grading into translucent agate",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Silicified volcanic deposits",
    where_found:       "Montana, Oregon, USA",
    diaphaneity:       "Opaque to translucent",
    rarity_score:      "Uncommon — transitional variety",
    stone_story:       "Jaspagate exists at the boundary — neither fully jasper nor agate, a stone of transition where opacity gives way to translucence.",
  },

  // ── AGATE (generic fallback) ──────────────────────────────────────
  "agate": {
    official_name:     "Agate",
    mineral_class:     "Silicates — Tectosilicates (Chalcedony group)",
    crystal_system: "Trigonal — microcrystalline (banded)",
    luster:            "Waxy to vitreous",
    chemical_formula:  "SiO₂",
    rock_composition:  "Banded microcrystalline quartz formed in volcanic vesicles",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Cenozoic",
    geological_era:    "Variable",
    rock_formation:    "Volcanic vesicle fills — basalt and rhyolite",
    where_found:       "Worldwide — Brazil, Uruguay, USA, Botswana, India, Germany",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Common to rare depending on variety",
    stone_story:       "Agate forms in the voids of ancient volcanic rock, layer by layer over millions of years — patience made visible in banded silica.",
  },

  // ── CHALCEDONY ────────────────────────────────────────────────────
  "chalcedony": {
    official_name:     "Chalcedony",
    mineral_class:     "Silicates — Tectosilicates",
    crystal_system: "Trigonal — microcrystalline",
    luster:            "Waxy to dull",
    chemical_formula:  "SiO₂",
    rock_composition:  "Microcrystalline quartz — base material for agate, jasper, and flint",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Cenozoic",
    geological_era:    "Variable",
    rock_formation:    "Hydrothermal veins and volcanic vesicles",
    where_found:       "Worldwide — USA, Brazil, India, Turkey, Namibia",
    diaphaneity:       "Translucent",
    rarity_score:      "Common — drusy varieties uncommon",
    stone_story:       "Chalcedony is the quiet foundation of the silica family — the base from which agate, jasper, and flint all emerge.",
  },

  // ── LABRADORITE ───────────────────────────────────────────────────
  "labradorite": {
    official_name:     "Labradorite",
    mineral_class:     "Silicates — Tectosilicates (Feldspar group — Plagioclase series)",
    crystal_system: "Triclinic — prismatic",
    luster:            "Vitreous to pearly with labradorescence",
    chemical_formula:  "(Ca,Na)(Al,Si)₄O₈ — 50–70% anorthite",
    rock_composition:  "Calcium-sodium feldspar with alternating albite and anorthite lamellae",
    specific_gravity:  "2.68–2.72",
    refractive_index:  "1.559–1.573",
    moh_hardness:      "6–6.5",
    fracture_pattern:  "Uneven to conchoidal",
    cleavage:          "Perfect in two directions at ~86°",
    tenacity:          "Brittle",
    geological_age:    "Precambrian — approximately 560 million years ago",
    geological_era:    "Proterozoic",
    rock_formation:    "Anorthosite intrusions and basaltic lava flows",
    where_found:       "Labrador, Canada; Finland (Spectrolite); Madagascar; Russia; Mexico",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Uncommon — high-flash specimens rare",
    stone_story:       "Labradorite's spectral flash — labradorescence — is caused by light scattering between microscopic feldspar lamellae. The aurora borealis, captured in stone.",
  },

  // ── OBSIDIAN ──────────────────────────────────────────────────────
  "fire obsidian": {
    official_name:     "Fire Obsidian",
    mineral_class:     "Volcanic glass — Mineraloid",
    crystal_system: "Amorphous — no crystal structure",
    luster:            "Vitreous with iridescent schiller",
    chemical_formula:  "SiO₂ (~70%) with Fe₃O₄ nanolayers",
    rock_composition:  "Rhyolitic volcanic glass with magnetite nanoparticle interference layers",
    specific_gravity:  "2.35–2.60",
    refractive_index:  "1.48–1.51",
    moh_hardness:      "5–5.5",
    fracture_pattern:  "Conchoidal — razor sharp",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Pleistocene — approximately 100,000–200,000 years ago",
    geological_era:    "Cenozoic — Quaternary",
    rock_formation:    "Rhyolitic lava flow — Glass Buttes volcanic complex",
    where_found:       "Glass Buttes, Lake County, Oregon, USA — only known source on earth",
    diaphaneity:       "Translucent",
    rarity_score:      "Rare — single-source locality worldwide",
    stone_story:       "Oregon fire obsidian is found in only one place on earth. Its rainbow iridescence comes from magnetite layers thinner than a wavelength of light — physics made visible.",
  },

  "obsidian": {
    official_name:     "Obsidian",
    mineral_class:     "Volcanic glass — Mineraloid",
    crystal_system: "Amorphous — no crystal structure",
    luster:            "Vitreous",
    chemical_formula:  "SiO₂ (~70%) with MgO and Fe₃O₄",
    rock_composition:  "Rhyolitic volcanic glass — rapidly quenched lava",
    specific_gravity:  "2.35–2.60",
    refractive_index:  "1.48–1.51",
    moh_hardness:      "5–5.5",
    fracture_pattern:  "Conchoidal — razor sharp",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Pleistocene to Holocene",
    geological_era:    "Cenozoic — Quaternary",
    rock_formation:    "Rhyolitic lava flows",
    where_found:       "Oregon, USA; Iceland; Mexico; Japan; Ethiopia",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Common — fire obsidian rare",
    stone_story:       "Obsidian is born in an instant — lava quenched so fast that crystals never form. One of nature's sharpest natural edges, used as tools for over a million years.",
  },

  // ── SERPENTINE ────────────────────────────────────────────────────
  "serpentine": {
    official_name:     "Serpentine",
    mineral_class:     "Silicates — Phyllosilicates (Serpentine group)",
    crystal_system: "Monoclinic — platy to fibrous",
    luster:            "Waxy to greasy",
    chemical_formula:  "Mg₃Si₂O₅(OH)₄",
    rock_composition:  "Hydrated magnesium silicate — altered ultramafic rock (peridotite/dunite)",
    specific_gravity:  "2.44–2.62",
    refractive_index:  "1.560–1.571",
    moh_hardness:      "3–5.5",
    fracture_pattern:  "Conchoidal to splintery",
    cleavage:          "Perfect in one direction",
    tenacity:          "Brittle to sectile",
    geological_age:    "Precambrian to Mesozoic",
    geological_era:    "Variable",
    rock_formation:    "Ophiolite sequences — oceanic crust thrust onto continents",
    where_found:       "California, Oregon, USA; Italy (Liguria); China; New Zealand; Afghanistan",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Common — gem-grade uncommon",
    stone_story:       "Serpentine forms deep in the earth's mantle and is thrust to the surface by tectonic forces — a stone from the planet's interior, carrying the chemistry of the deep earth.",
  },
  // ── THUNDEREGG ────────────────────────────────────────────────────
  "thunderegg": {
  // ── SNOW QUARTZ ───────────────────────────────────────────────────
  "snow quartz": {
    official_name:     "Snow Quartz (Milky Quartz)",
    mineral_class:     "Silicates — Tectosilicates",
    crystal_system: "Trigonal — hexagonal prisms",
    luster:            "Waxy to vitreous",
    chemical_formula:  "SiO₂",
    rock_composition:  "Crystalline quartz with microscopic fluid and gas inclusions causing opacity",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    moh_hardness:      "7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to Cenozoic",
    geological_era:    "Variable",
    rock_formation:    "Hydrothermal veins and pegmatites",
    where_found:       "Worldwide — USA, Brazil, India, Alps, Madagascar",
    diaphaneity:       "Translucent — milky white",
    rarity_score:      "Common",
    stone_story:       "Snow quartz gets its milky opacity from microscopic water and gas inclusions trapped during crystal growth — clouds frozen in stone.",
  },

  // ── QUARTZ (generic) ──────────────────────────────────────────────
  "quartz": {
    official_name:     "Quartz",
    mineral_class:     "Silicates — Tectosilicates",
    crystal_system: "Trigonal — hexagonal prisms with pyramidal terminations",
    luster:            "Vitreous",
    chemical_formula:  "SiO₂",
    rock_composition:  "Crystalline silicon dioxide — second most abundant mineral in earth's crust",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    moh_hardness:      "7",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to present",
    geological_era:    "Variable",
    rock_formation:    "Igneous, metamorphic, and sedimentary — ubiquitous",
    where_found:       "Worldwide",
    diaphaneity:       "Transparent to translucent",
    rarity_score:      "Common — gem varieties uncommon to rare",
    stone_story:       "Quartz is the backbone of the mineral world — the second most abundant mineral in the earth's crust, found on every continent in every geological setting.",
  },

  // ── GNEISS ────────────────────────────────────────────────────────
  "gneiss": {
    official_name:     "Gneiss",
    mineral_class:     "Metamorphic rock — Quartz, Feldspar, Mica, Hornblende",
    crystal_system: "N/A — polymineralic foliated rock",
    luster:            "Vitreous to pearly",
    chemical_formula:  "N/A — variable composition",
    rock_composition:  "Banded quartz, feldspar, and mica with foliation from high-grade metamorphism",
    specific_gravity:  "2.65–2.80",
    refractive_index:  "N/A",
    moh_hardness:      "6–7",
    fracture_pattern:  "Uneven — follows foliation planes",
    cleavage:          "Varies by mineral component",
    tenacity:          "Brittle",
    geological_age:    "Precambrian — often 1–4 billion years old",
    geological_era:    "Archean to Proterozoic",
    rock_formation:    "High-grade metamorphic terranes — deep crustal roots",
    where_found:       "Pacific Northwest USA, Canadian Shield, Scandinavia, Scotland",
    diaphaneity:       "Opaque",
    rarity_score:      "Common rock — gem-grade lapidary specimens uncommon",
    stone_story:       "Gneiss is among the oldest material on earth — sedimentary or igneous rock transformed by extreme heat and pressure over billions of years into banded stone.",
  },

  // ── SILTSTONE ─────────────────────────────────────────────────────
  "siltstone": {
    official_name:     "Siltstone",
    mineral_class:     "Sedimentary rock — Quartz, Feldspar, Clay minerals",
    crystal_system: "N/A — clastic sedimentary rock",
    luster:            "Dull to silky",
    chemical_formula:  "N/A — variable",
    rock_composition:  "Compacted silt particles (0.002–0.063mm) — quartz, feldspar, clay minerals",
    specific_gravity:  "2.20–2.70",
    refractive_index:  "N/A",
    moh_hardness:      "3–5",
    fracture_pattern:  "Uneven — fissile along bedding planes",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene — ancient lake bed deposits",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Ancient lacustrine (lake bed) deposits — Pacific Northwest basin",
    where_found:       "Ancient lake bed formations, Pacific Northwest, USA",
    diaphaneity:       "Opaque",
    rarity_score:      "Common rock — lapidary-grade specimens uncommon",
    stone_story:       "Ancient lake bed siltstone is time made tangible — layers of sediment settled in still water millions of years ago, compressed into stone by the weight of time.",
  },

  // ── VARISCITE ─────────────────────────────────────────────────────
  "variscite": {
    official_name:     "Variscite",
    mineral_class:     "Phosphates — Variscite group",
    crystal_system: "Orthorhombic — tabular crystals, usually massive",
    luster:            "Waxy to vitreous",
    chemical_formula:  "AlPO₄·2H₂O",
    rock_composition:  "Hydrated aluminum phosphate — formed by phosphate-rich water reacting with aluminum minerals",
    specific_gravity:  "2.20–2.57",
    refractive_index:  "1.560–1.594",
    moh_hardness:      "3.5–4.5",
    fracture_pattern:  "Conchoidal to uneven",
    cleavage:          "Good in one direction",
    tenacity:          "Brittle",
    geological_age:    "Tertiary — approximately 30–50 million years ago",
    geological_era:    "Cenozoic — Paleogene",
    rock_formation:    "Phosphate replacement deposits in aluminum-rich host rock",
    where_found:       "Fairfield, Utah, USA; Lucin, Nevada, USA; Queensland, Australia; Saxony, Germany",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Rare — fine Utah specimens highly collectible",
    stone_story:       "Rarer than turquoise and often mistaken for it — variscite is a soft phosphate mineral in shades of apple green found in only a handful of places on earth.",
  },

  // ── FELDSPAR ──────────────────────────────────────────────────────
  "feldspar": {
    official_name:     "Feldspar",
    mineral_class:     "Silicates — Tectosilicates (Feldspar group)",
    crystal_system: "Triclinic or Monoclinic — prismatic",
    luster:            "Vitreous to pearly",
    chemical_formula:  "KAlSi₃O₈ / NaAlSi₃O₈ / CaAl₂Si₂O₈",
    rock_composition:  "Framework silicate — most abundant mineral group in earth's crust",
    specific_gravity:  "2.55–2.76",
    refractive_index:  "1.518–1.588",
    moh_hardness:      "6–6.5",
    fracture_pattern:  "Uneven to conchoidal",
    cleavage:          "Perfect in two directions",
    tenacity:          "Brittle",
    geological_age:    "Precambrian to present",
    geological_era:    "Variable",
    rock_formation:    "Igneous and metamorphic rocks — granites, pegmatites, gneisses",
    where_found:       "Worldwide — USA, Norway, Finland, Madagascar, India",
    diaphaneity:       "Translucent to opaque",
    rarity_score:      "Common — gem varieties uncommon",
    stone_story:       "Feldspar is the most abundant mineral group in the earth's crust — the foundation beneath our feet, occasionally revealing beauty in purple, violet, and spectral flash.",
  },

  // ── DALMATIAN STONE ───────────────────────────────────────────────
  "dalmatian stone": {
    official_name:     "Dalmatian Stone (Dalmatian Jasper)",
    mineral_class:     "Igneous rock — Feldspar, Quartz, Arfvedsonite, Hornblende",
    crystal_system: "N/A — polymineralic igneous rock",
    luster:            "Dull to vitreous",
    chemical_formula:  "N/A — variable",
    rock_composition:  "Pale feldspar and quartz matrix with black arfvedsonite or tourmaline phenocrysts",
    specific_gravity:  "2.60–2.80",
    refractive_index:  "N/A",
    moh_hardness:      "6–7",
    fracture_pattern:  "Uneven",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Cretaceous to Paleogene — approximately 65–100 million years ago",
    geological_era:    "Mesozoic to Cenozoic",
    rock_formation:    "Felsic igneous intrusion — aplite or rhyolite",
    where_found:       "Chihuahua, Mexico; Pacific Northwest river gravels, USA",
    diaphaneity:       "Opaque",
    rarity_score:      "Uncommon — PNW river specimens rare",
    stone_story:       "Dalmatian stone's bold black spots are crystals of arfvedsonite set in pale feldspar — a playful pattern born from slow-cooling magma deep in the earth.",
  },


    official_name:     "Thunderegg",
    mineral_class:     "Volcanic nodule — Agate / Chalcedony / Jasper interior",
    crystal_system: "Trigonal — microcrystalline interior fill",
    luster:            "Dull exterior — waxy to vitreous interior",
    chemical_formula:  "SiO₂ interior fill",
    rock_composition:  "Rhyolitic ash flow tuff exterior with silica-filled interior cavity",
    specific_gravity:  "2.40–2.65",
    refractive_index:  "1.530–1.540",
    moh_hardness:      "6.5–7 interior",
    fracture_pattern:  "Conchoidal interior",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Miocene — approximately 10–15 million years ago",
    geological_era:    "Cenozoic — Neogene",
    rock_formation:    "Rhyolitic ash flow tuffs — Pacific Northwest volcanic fields",
    where_found:       "Oregon (state rock), Washington, Idaho, USA; New Zealand; Germany",
    diaphaneity:       "Opaque exterior — translucent to opaque interior",
    rarity_score:      "Uncommon — patterned interiors collectible",
    stone_story:       "Oregon's state rock — a rhyolite nodule filled with agate or chalcedony. Named by the Warm Springs people who believed they were hurled by thunder spirits during storms.",
  },

  // ── CONGLOMERATE ──────────────────────────────────────────────────
  "conglomerate": {
    official_name:     "River Conglomerate",
    mineral_class:     "Sedimentary rock — mixed clastic composition",
    crystal_system: "N/A — clastic sedimentary rock",
    luster:            "Dull to waxy",
    chemical_formula:  "N/A — variable",
    rock_composition:  "Rounded gravel clasts of mixed lithology cemented by silica or calcite matrix",
    specific_gravity:  "2.20–2.80",
    refractive_index:  "N/A",
    moh_hardness:      "4–7 variable",
    fracture_pattern:  "Uneven — follows clast boundaries",
    cleavage:          "None",
    tenacity:          "Brittle",
    geological_age:    "Pleistocene — glacial outwash deposits",
    geological_era:    "Cenozoic — Quaternary",
    rock_formation:    "Glacial outwash and river terrace deposits",
    where_found:       "Spokane River, Washington State, USA",
    diaphaneity:       "Opaque",
    rarity_score:      "Common rock — lapidary mosaic specimens uncommon",
    stone_story:       "River conglomerate is a mosaic of journeys — stones from different origins tumbled together by ancient glacial meltwater and cemented into one unified piece.",
  },

};

// ── LOOKUP FUNCTION ───────────────────────────────────────────────────────────
// Matches product title to stone type — most specific match wins
// Case-insensitive partial match on stone name

export function lookupStone(title) {
  if (!title) return null;
  const t = title.toLowerCase();

  // Sort keys longest first so specific entries beat generic ones
  const keys = Object.keys(GEO_LIBRARY).sort((a, b) => b.length - a.length);

  for (const key of keys) {
    if (t.includes(key)) {
      return GEO_LIBRARY[key];
    }
  }

  return null;
}

export default GEO_LIBRARY;
