// Rockhound Studio — PNW Geology Library
// Add new stones by copying an existing entry and updating the fields.

export const GEO_LIBRARY = {
  // ── QUARTZ FAMILY ─────────────────────────────────────────────
  "quartz": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Opaque",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Igneous, Metamorphic, Sedimentary",
  },
  "clear quartz": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent",
    primary_color:     "Colorless",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Igneous, Metamorphic, Sedimentary",
  },
  "rose quartz": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous to Waxy",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    primary_color:     "Pink",
    geological_era:    "Precambrian",
    rock_formation:    "Pegmatite",
  },
  "smoky quartz": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Translucent",
    primary_color:     "Brown to Black",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Igneous, Metamorphic",
  },
  "amethyst": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Translucent",
    primary_color:     "Purple",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Igneous Geodes, Alluvial Deposits",
  },
  "citrine": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal",
    moh_hardness:      "7",
    luster:            "Vitreous",
    specific_gravity:  "2.65",
    refractive_index:  "1.544–1.553",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent",
    primary_color:     "Yellow to Orange",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Igneous, Metamorphic",
  },

  // ── CHALCEDONY / AGATE FAMILY ─────────────────────────────────
  "chalcedony": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Volcanic, Sedimentary",
  },
  "agate": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Volcanic Cavities, Sedimentary",
  },
  "montana agate": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    primary_color:     "Clear to White with Black Dendritic Inclusions",
    origin_location:   "Yellowstone River Valley, Montana, USA",
    geological_age:    "Eocene",
    geological_era:    "Cenozoic",
    rock_formation:    "Alluvial Gravel Deposits",
    where_found:       "Yellowstone River, Montana",
  },
  "blue lace agate": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    primary_color:     "Pale Blue with White Banding",
    geological_era:    "Precambrian",
    rock_formation:    "Volcanic",
  },
  "fire agate": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy to Resinous",
    specific_gravity:  "2.58–2.64",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    primary_color:     "Brown with Iridescent Fire",
    origin_location:   "Arizona, New Mexico, USA; Mexico",
    geological_era:    "Cenozoic",
    rock_formation:    "Volcanic Hydrothermal",
  },

  // ── JASPER FAMILY ─────────────────────────────────────────────
  "jasper": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Dull to Waxy",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Sedimentary, Volcanic",
  },
  "picture jasper": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Dull to Waxy",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Tan, Brown, Cream with Landscape Patterns",
    origin_location:   "Oregon, Idaho, USA",
    geological_era:    "Cenozoic",
    rock_formation:    "Volcanic Sedimentary",
  },
  "ocean jasper": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Waxy",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent to Opaque",
    primary_color:     "Multi-color with Orbicular Patterns",
    origin_location:   "Madagascar",
    geological_era:    "Precambrian",
    rock_formation:    "Volcanic",
  },
  "red jasper": {
    mineral_class:     "Silicate",
    chemical_formula:  "SiO₂",
    crystal_structure: "Trigonal (Microcrystalline)",
    moh_hardness:      "6.5–7",
    luster:            "Dull to Waxy",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.540",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Red",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Sedimentary, Metamorphic",
  },

  // ── PETRIFIED WOOD ────────────────────────────────────────────
  "petrified wood": {
    mineral_class:     "Silicate (Replacement)",
    chemical_formula:  "SiO₂",
    crystal_structure: "Amorphous to Microcrystalline",
    moh_hardness:      "6.5–7",
    luster:            "Dull to Waxy",
    specific_gravity:  "2.58–2.91",
    refractive_index:  "1.530–1.540",
    fracture_pattern:  "Conchoidal to Irregular",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    geological_era:    "Triassic to Miocene",
    rock_formation:    "Silicified Organic Material in Sedimentary Deposits",
    where_found:       "Pacific Northwest, USA",
  },

  // ── OBSIDIAN ──────────────────────────────────────────────────
  "obsidian": {
    mineral_class:     "Volcanic Glass (Silicate)",
    chemical_formula:  "SiO₂ (with MgO, Fe₃O₄)",
    crystal_structure: "Amorphous",
    moh_hardness:      "5–5.5",
    luster:            "Vitreous",
    specific_gravity:  "2.35–2.60",
    refractive_index:  "1.45–1.55",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Opaque",
    primary_color:     "Black",
    geological_era:    "Cenozoic",
    rock_formation:    "Rhyolitic Lava Flows",
    where_found:       "Pacific Northwest, USA; Iceland; Mexico",
  },
  "mahogany obsidian": {
    mineral_class:     "Volcanic Glass (Silicate)",
    chemical_formula:  "SiO₂ (with Fe₃O₄)",
    crystal_structure: "Amorphous",
    moh_hardness:      "5–5.5",
    luster:            "Vitreous",
    specific_gravity:  "2.35–2.60",
    refractive_index:  "1.45–1.55",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Black and Mahogany Brown",
    geological_era:    "Cenozoic",
    rock_formation:    "Rhyolitic Lava Flows",
  },
  "rainbow obsidian": {
    mineral_class:     "Volcanic Glass (Silicate)",
    chemical_formula:  "SiO₂",
    crystal_structure: "Amorphous",
    moh_hardness:      "5–5.5",
    luster:            "Vitreous with Iridescence",
    specific_gravity:  "2.35–2.60",
    refractive_index:  "1.45–1.55",
    fracture_pattern:  "Conchoidal",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Black with Rainbow Sheen",
    geological_era:    "Cenozoic",
    rock_formation:    "Rhyolitic Lava Flows",
  },

  // ── BASALT / VOLCANIC ─────────────────────────────────────────
  "basalt": {
    mineral_class:     "Igneous Rock",
    chemical_formula:  "Complex Silicate",
    crystal_structure: "Fine-grained Crystalline",
    moh_hardness:      "5–6",
    luster:            "Dull",
    specific_gravity:  "2.8–3.0",
    refractive_index:  "N/A",
    fracture_pattern:  "Irregular",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Dark Gray to Black",
    geological_era:    "Cenozoic",
    rock_formation:    "Volcanic Lava Flows",
    where_found:       "Pacific Northwest, USA",
  },

  // ── FELDSPAR FAMILY ───────────────────────────────────────────
  "labradorite": {
    mineral_class:     "Silicate (Feldspar)",
    chemical_formula:  "NaAlSi₃O₈–CaAl₂Si₂O₈",
    crystal_structure: "Triclinic",
    moh_hardness:      "6–6.5",
    luster:            "Vitreous to Pearly",
    specific_gravity:  "2.68–2.72",
    refractive_index:  "1.559–1.573",
    fracture_pattern:  "Conchoidal to Uneven",
    cleavage:          "Perfect in Two Directions",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent to Opaque",
    primary_color:     "Gray with Blue-Green Labradorescence",
    geological_era:    "Precambrian",
    rock_formation:    "Igneous, Metamorphic",
  },
  "moonstone": {
    mineral_class:     "Silicate (Feldspar)",
    chemical_formula:  "KAlSi₃O₈",
    crystal_structure: "Monoclinic",
    moh_hardness:      "6–6.5",
    luster:            "Pearly to Adularescent",
    specific_gravity:  "2.56–2.62",
    refractive_index:  "1.518–1.526",
    fracture_pattern:  "Conchoidal",
    cleavage:          "Perfect in Two Directions",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent",
    primary_color:     "White to Colorless with Blue Sheen",
    geological_era:    "Precambrian",
    rock_formation:    "Pegmatite, Metamorphic",
  },

  // ── CARBONATE FAMILY ──────────────────────────────────────────
  "calcite": {
    mineral_class:     "Carbonate",
    chemical_formula:  "CaCO₃",
    crystal_structure: "Trigonal",
    moh_hardness:      "3",
    luster:            "Vitreous to Resinous",
    specific_gravity:  "2.71",
    refractive_index:  "1.486–1.658",
    fracture_pattern:  "Conchoidal",
    cleavage:          "Perfect Rhombohedral",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Opaque",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Sedimentary, Metamorphic, Hydrothermal",
  },

  // ── MISC PNW STONES ───────────────────────────────────────────
  "serpentine": {
    mineral_class:     "Silicate (Phyllosilicate)",
    chemical_formula:  "Mg₃Si₂O₅(OH)₄",
    crystal_structure: "Monoclinic",
    moh_hardness:      "3–5",
    luster:            "Waxy to Greasy",
    specific_gravity:  "2.44–2.62",
    refractive_index:  "1.560–1.571",
    fracture_pattern:  "Conchoidal to Splintery",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent to Opaque",
    primary_color:     "Green",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Metamorphic (Ultramafic)",
    where_found:       "Pacific Northwest, USA",
  },
  "turquoise": {
    mineral_class:     "Phosphate",
    chemical_formula:  "CuAl₆(PO₄)₄(OH)₈·4H₂O",
    crystal_structure: "Triclinic",
    moh_hardness:      "5–6",
    luster:            "Waxy to Dull",
    specific_gravity:  "2.60–2.90",
    refractive_index:  "1.610–1.650",
    fracture_pattern:  "Conchoidal to Smooth",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Blue to Green",
    geological_era:    "Variable",
    rock_formation:    "Hydrothermal, Arid Oxidized Zones",
  },
  "malachite": {
    mineral_class:     "Carbonate",
    chemical_formula:  "Cu₂(CO₃)(OH)₂",
    crystal_structure: "Monoclinic",
    moh_hardness:      "3.5–4",
    luster:            "Vitreous to Silky",
    specific_gravity:  "3.6–4.05",
    refractive_index:  "1.655–1.909",
    fracture_pattern:  "Subconchoidal to Uneven",
    cleavage:          "Perfect",
    tenacity:          "Brittle",
    diaphaneity:       "Translucent to Opaque",
    primary_color:     "Green with Banding",
    geological_era:    "Variable",
    rock_formation:    "Oxidized Copper Deposits",
  },
  "lapis lazuli": {
    mineral_class:     "Metamorphic Rock (Lazurite)",
    chemical_formula:  "(Na,Ca)₈(AlSiO₄)₆(SO₄,S,Cl)₂",
    crystal_structure: "Isometric",
    moh_hardness:      "5–6",
    luster:            "Dull to Waxy",
    specific_gravity:  "2.7–2.9",
    refractive_index:  "1.500",
    fracture_pattern:  "Irregular",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Deep Blue with Gold Pyrite Flecks",
    origin_location:   "Afghanistan",
    geological_era:    "Precambrian",
    rock_formation:    "Metamorphic (Contact)",
  },
  "garnet": {
    mineral_class:     "Silicate (Nesosilicate)",
    chemical_formula:  "X₃Y₂(SiO₄)₃",
    crystal_structure: "Isometric",
    moh_hardness:      "6.5–7.5",
    luster:            "Vitreous to Resinous",
    specific_gravity:  "3.5–4.3",
    refractive_index:  "1.714–1.888",
    fracture_pattern:  "Conchoidal to Irregular",
    cleavage:          "None",
    tenacity:          "Brittle",
    diaphaneity:       "Transparent to Opaque",
    primary_color:     "Red",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Metamorphic, Igneous",
  },
  "pyrite": {
    mineral_class:     "Sulfide",
    chemical_formula:  "FeS₂",
    crystal_structure: "Isometric",
    moh_hardness:      "6–6.5",
    luster:            "Metallic",
    specific_gravity:  "4.95–5.10",
    refractive_index:  "N/A",
    fracture_pattern:  "Conchoidal to Uneven",
    cleavage:          "Indistinct",
    tenacity:          "Brittle",
    diaphaneity:       "Opaque",
    primary_color:     "Brass Yellow",
    geological_era:    "Precambrian to Recent",
    rock_formation:    "Hydrothermal, Sedimentary, Metamorphic",
  },
};

/**
 * Look up a stone by name. Tries exact match first, then partial match.
 * Returns matched data object or null.
 */
export function lookupStone(title) {
  if (!title) return null;
  const lower = title.toLowerCase().trim();

  // Exact match
  if (GEO_LIBRARY[lower]) return { ...GEO_LIBRARY[lower] };

  // Partial match — find first key contained in the title
  const match = Object.keys(GEO_LIBRARY).find(key => lower.includes(key));
  return match ? { ...GEO_LIBRARY[match] } : null;
}
