import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log(`Starting TRUE PNW God-Mode Lapidary Database Seed (100 Stones)...`);

  await prisma.stoneProfile.deleteMany({});

  const stones = [
    // --- THE JASPERS (14) ---
    { stoneName: 'Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous to Dull', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.5 - 2.9', diaphaneity: 'Opaque' },
    { stoneName: 'Picture Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.5 - 2.9', diaphaneity: 'Opaque' },
    { stoneName: 'Owyhee Jasper', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Biggs Jasper', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Morrisonite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Red Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Yellow Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Ocean Jasper', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Mookaite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Mesozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous to Dull', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Brecciated Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Dalmatian Stone', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Other', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '5.5 - 7.0', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Bloodstone', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Bumblebee Jasper', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.0 - 4.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Kambaba Jasper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    
    // --- THE AGATES & CHALCEDONIES (15) ---
    { stoneName: 'Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.58 - 2.64', diaphaneity: 'Translucent' },
    { stoneName: 'Montana Agate', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Botswana Agate', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Ellensburg Blue Agate', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Plume Agate', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Moss Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Tree Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Lace Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Crazy Lace Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Blue Lace Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Dendritic Agate', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent' },
    { stoneName: 'Fire Agate', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Chalcedony', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.59 - 2.61', diaphaneity: 'Translucent' },
    { stoneName: 'Carnelian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Igneous', hardness: '6.5 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.59', diaphaneity: 'Translucent' },
    { stoneName: 'Chrysoprase', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.58 - 2.64', diaphaneity: 'Translucent' },

    // --- MACROCRYSTALLINE QUARTZ (11) ---
    { stoneName: 'Quartz', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Amethyst', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Citrine', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Rose Quartz', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Translucent' },
    { stoneName: 'Smoky Quartz', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Prasiolite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Tourmalinated Quartz', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent with Inclusions' },
    { stoneName: 'Rutilated Quartz', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Transparent with Inclusions' },
    { stoneName: 'Tiger\'s Eye', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '6.5 - 7.0', luster: 'Silky', fracture: 'Fibrous', cleavage: 'None', specificGravity: '2.64 - 2.71', diaphaneity: 'Opaque' },
    { stoneName: 'Hawk\'s Eye', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '6.5 - 7.0', luster: 'Silky', fracture: 'Fibrous', cleavage: 'None', specificGravity: '2.64', diaphaneity: 'Opaque' },
    { stoneName: 'Aventurine', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '6.5 - 7.0', luster: 'Vitreous to Glistening', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.64 - 2.69', diaphaneity: 'Translucent to Opaque' },

    // --- PNW FORAGING & COMMON RIVER ROCKS (9) ---
    { stoneName: 'Petrified Wood', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Jasper', rockFormation: 'Sedimentary', hardness: '6.5 - 7.0', luster: 'Waxy to Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.58 - 2.91', diaphaneity: 'Opaque' },
    { stoneName: 'Basalt', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.5 - 6.0', luster: 'Dull', fracture: 'Uneven', cleavage: 'None', specificGravity: '2.8 - 3.0', diaphaneity: 'Opaque' },
    { stoneName: 'Rhyolite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 7.0', luster: 'Dull to Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.4 - 2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Thunderegg', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 7.0', luster: 'Varies', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.5 - 2.7', diaphaneity: 'Opaque' },
    { stoneName: 'Granite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 7.0', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'None', specificGravity: '2.6 - 2.8', diaphaneity: 'Opaque' },
    { stoneName: 'Quartzite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.65', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Argillite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Sedimentary', hardness: '3.0 - 4.0', luster: 'Dull', fracture: 'Uneven', cleavage: 'Good', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Dallasite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Mesozoic', mineralClass: 'Silicates', rockComposition: 'Andesite', rockFormation: 'Igneous', hardness: '6.0 - 7.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6 - 2.8', diaphaneity: 'Opaque' },
    { stoneName: 'Pumice', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.5 - 6.0', luster: 'Dull', fracture: 'Uneven', cleavage: 'None', specificGravity: '0.2 - 0.3', diaphaneity: 'Opaque' },

    // --- THE FELDSPARS (6) ---
    { stoneName: 'Feldspar', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous to Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.56 - 2.76', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Labradorite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Andesite', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous to Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.68 - 2.72', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Moonstone', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous to Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.56 - 2.59', diaphaneity: 'Translucent' },
    { stoneName: 'Sunstone', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Andesite', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.62 - 2.65', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Amazonite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.56 - 2.58', diaphaneity: 'Opaque' },
    { stoneName: 'Larvikite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Paleozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.7 - 2.8', diaphaneity: 'Opaque' },

    // --- OBSIDIANS (6) ---
    { stoneName: 'Obsidian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Snowflake Obsidian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Opaque' },
    { stoneName: 'Mahogany Obsidian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Opaque' },
    { stoneName: 'Rainbow Obsidian', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Opaque' },
    { stoneName: 'Gold Sheen Obsidian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Opaque' },
    { stoneName: 'Silver Sheen Obsidian', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Obsidian', rockFormation: 'Igneous', hardness: '5.0 - 5.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.35 - 2.60', diaphaneity: 'Opaque' },

    // --- SOFT / CABBING & COPPER BEAUTIES (15) ---
    { stoneName: 'Malachite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Paleozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.5 - 4.0', luster: 'Silky to Dull', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '3.6 - 4.0', diaphaneity: 'Opaque' },
    { stoneName: 'Chrysocolla', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '2.5 - 3.5', luster: 'Vitreous to Earthy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.0 - 2.4', diaphaneity: 'Opaque' },
    { stoneName: 'Azurite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Monoclinic', geologicalEra: 'Paleozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.5 - 4.0', luster: 'Vitreous to Dull', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '3.7 - 3.9', diaphaneity: 'Opaque' },
    { stoneName: 'Turquoise', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Triclinic', geologicalEra: 'Cenozoic', mineralClass: 'Phosphates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '5.0 - 6.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'Good', specificGravity: '2.60 - 2.90', diaphaneity: 'Opaque' },
    { stoneName: 'Variscite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Phosphates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '4.0 - 5.0', luster: 'Waxy', fracture: 'Conchoidal', cleavage: 'Good', specificGravity: '2.5 - 2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Serpentine', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '2.5 - 5.5', luster: 'Greasy to Waxy', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '2.5 - 2.6', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Rhodochrosite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.5 - 4.0', luster: 'Vitreous to Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '3.5 - 3.7', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Fluorite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Other', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '4.0', luster: 'Vitreous', fracture: 'Subconchoidal', cleavage: 'Perfect', specificGravity: '3.0 - 3.3', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Calcite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Paleozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '2.7', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Howlite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Cenozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.5', luster: 'Dull to Earthy', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.5 - 2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Magnesite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Paleozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.5 - 4.5', luster: 'Dull', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '3.0 - 3.2', diaphaneity: 'Opaque' },
    { stoneName: 'Apatite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Hexagonal', geologicalEra: 'Paleozoic', mineralClass: 'Phosphates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '5.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Indistinct', specificGravity: '3.1 - 3.2', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Lepidolite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '2.5 - 3.0', luster: 'Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '2.8 - 2.9', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Onyx Marble', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Cenozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '3.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '2.7', diaphaneity: 'Translucent' },
    { stoneName: 'Smithsonite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Paleozoic', mineralClass: 'Carbonates', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '4.5', luster: 'Pearly', fracture: 'Uneven', cleavage: 'Perfect', specificGravity: '4.3 - 4.4', diaphaneity: 'Translucent to Opaque' },
    
    // --- NATIVE METALS & IRON (6) ---
    { stoneName: 'Gold', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Other', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '2.5 - 3.0', luster: 'Metallic', fracture: 'Hackly', cleavage: 'None', specificGravity: '19.3', diaphaneity: 'Opaque' },
    { stoneName: 'Silver', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Other', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '2.5 - 3.0', luster: 'Metallic', fracture: 'Hackly', cleavage: 'None', specificGravity: '10.5', diaphaneity: 'Opaque' },
    { stoneName: 'Copper', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Other', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '2.5 - 3.0', luster: 'Metallic', fracture: 'Hackly', cleavage: 'None', specificGravity: '8.9', diaphaneity: 'Opaque' },
    { stoneName: 'Hematite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Oxides', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '5.5 - 6.5', luster: 'Metallic', fracture: 'Uneven', cleavage: 'None', specificGravity: '5.0 - 5.3', diaphaneity: 'Opaque' },
    { stoneName: 'Pyrite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Other', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '6.0 - 6.5', luster: 'Metallic', fracture: 'Conchoidal', cleavage: 'Poor', specificGravity: '4.95 - 5.10', diaphaneity: 'Opaque' },
    { stoneName: 'Ironstone Matrix', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Other', mineralClass: 'Oxides', rockComposition: 'Other', rockFormation: 'Sedimentary', hardness: '5.5 - 6.5', luster: 'Dull to Earthy', fracture: 'Uneven', cleavage: 'None', specificGravity: '3.0 - 4.0', diaphaneity: 'Opaque' },

    // --- TOUGH CABBING & HIGH END SILICATES (18) ---
    { stoneName: 'Jadeite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Monoclinic', geologicalEra: 'Mesozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '6.5 - 7.0', luster: 'Vitreous to Greasy', fracture: 'Splintery', cleavage: 'Good', specificGravity: '3.24 - 3.43', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Nephrite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '6.0 - 6.5', luster: 'Vitreous to Greasy', fracture: 'Splintery', cleavage: 'Good', specificGravity: '2.90 - 3.03', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Rhodonite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Triclinic', geologicalEra: 'Paleozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '5.5 - 6.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '3.5 - 3.7', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Lapis Lazuli', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '5.0 - 5.5', luster: 'Vitreous to Greasy', fracture: 'Uneven', cleavage: 'Imperfect', specificGravity: '2.7 - 2.9', diaphaneity: 'Opaque' },
    { stoneName: 'Sodalite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '5.5 - 6.0', luster: 'Vitreous to Greasy', fracture: 'Conchoidal', cleavage: 'Poor', specificGravity: '2.14 - 2.40', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Unakite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Monoclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Metamorphic', hardness: '6.0 - 7.0', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Good', specificGravity: '3.3 - 3.5', diaphaneity: 'Opaque' },
    { stoneName: 'Charoite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Monoclinic', geologicalEra: 'Mesozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '5.0 - 6.0', luster: 'Vitreous to Pearly', fracture: 'Conchoidal', cleavage: 'Good', specificGravity: '2.54 - 2.58', diaphaneity: 'Translucent to Opaque' },
    { stoneName: 'Pietersite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Metamorphic', hardness: '6.5 - 7.0', luster: 'Silky', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '2.6', diaphaneity: 'Opaque' },
    { stoneName: 'Prehnite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Mesozoic', mineralClass: 'Silicates', rockComposition: 'Other', rockFormation: 'Igneous', hardness: '6.0 - 6.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Good', specificGravity: '2.8 - 2.9', diaphaneity: 'Translucent' },
    { stoneName: 'Kyanite', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Triclinic', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '4.5 - 7.0', luster: 'Vitreous to Pearly', fracture: 'Splintery', cleavage: 'Perfect', specificGravity: '3.53 - 3.65', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Dumortierite', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '7.0 - 8.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Good', specificGravity: '3.2 - 3.4', diaphaneity: 'Opaque' },
    { stoneName: 'Garnet', authenticity: 'Genuine', rarity: 'Common', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '6.5 - 7.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '3.5 - 4.3', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Star Garnet', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Silicates', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '6.5 - 7.5', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'None', specificGravity: '3.5 - 4.3', diaphaneity: 'Opaque' },
    { stoneName: 'Tourmaline', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Trigonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.0 - 7.5', luster: 'Vitreous', fracture: 'Uneven', cleavage: 'Indistinct', specificGravity: '3.0 - 3.26', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Beryl', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Hexagonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.5 - 8.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Imperfect', specificGravity: '2.63 - 2.90', diaphaneity: 'Transparent to Opaque' },
    { stoneName: 'Aquamarine', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Hexagonal', geologicalEra: 'Precambrian', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '7.5 - 8.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Imperfect', specificGravity: '2.68 - 2.74', diaphaneity: 'Transparent to Translucent' },
    { stoneName: 'Topaz', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Other', mineralClass: 'Silicates', rockComposition: 'Granite', rockFormation: 'Igneous', hardness: '8.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Perfect', specificGravity: '3.49 - 3.57', diaphaneity: 'Transparent' },
    { stoneName: 'Spinel', authenticity: 'Genuine', rarity: 'Rare', crystalSystem: 'Other', geologicalEra: 'Paleozoic', mineralClass: 'Oxides', rockComposition: 'Schist', rockFormation: 'Metamorphic', hardness: '8.0', luster: 'Vitreous', fracture: 'Conchoidal', cleavage: 'Indistinct', specificGravity: '3.54 - 3.63', diaphaneity: 'Transparent to Opaque' }
  ];

  for (const stone of stones) {
    const profile = await prisma.stoneProfile.create({
      data: stone,
    });
    console.log(`Created dictionary entry for: ${profile.stoneName} (Mohs: ${profile.hardness})`);
  }

  console.log(`\n======================================================`);
  console.log(`💥 SUCCESS: Seeded exactly ${stones.length} PNW Master Lapidary Stones!`);
  console.log(`======================================================\n`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
